# Generated by Django 5.1.4 on 2025-01-14 00:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Courier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_id', models.CharField(blank=True, max_length=50, unique=True)),
                ('order_type', models.CharField(max_length=50)),
                ('delivery_type', models.CharField(max_length=50)),
                ('order_date', models.DateTimeField(auto_now=True)),
                ('package_name', models.CharField(max_length=100)),
                ('weight', models.CharField(max_length=50)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('reference', models.CharField(blank=True, max_length=50, null=True)),
                ('instruction', models.CharField(blank=True, max_length=100, null=True)),
                ('customer_name', models.CharField(max_length=200)),
                ('customer_address', models.TextField()),
                ('customer_phone', models.CharField(max_length=15)),
                ('customer_alt_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('cod_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CourierPOD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pod_image', models.ImageField(blank=True, null=True, upload_to='courier_pods/')),
            ],
        ),
        migrations.CreateModel(
            name='CourierStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Booked by', 'Booked by'), ('Cancel', 'Cancel'), ('Packed for', 'Packed for'), ('Received by', 'Received by'), ('Sent to', 'Sent to'), ('In destination', 'In destination'), ('Out for delivery', 'Out for delivery'), ('Delivered', 'Delivered')], max_length=50)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('additional_info', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_name', models.CharField(max_length=200)),
                ('vendor_address', models.TextField()),
                ('vendor_phone', models.CharField(max_length=15)),
                ('vendor_alt_phone', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courierapp.branch')),
            ],
        ),
    ]
