# Generated by Django 5.1.4 on 2025-01-14 00:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courierapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='courier',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='courier',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courierapp.branch'),
        ),
        migrations.AddField(
            model_name='courierpod',
            name='courier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pods', to='courierapp.courier'),
        ),
        migrations.AddField(
            model_name='courierpod',
            name='updated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='courierstatus',
            name='courier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='courierapp.courier'),
        ),
        migrations.AddField(
            model_name='courierstatus',
            name='location_branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courierapp.branch'),
        ),
        migrations.AddField(
            model_name='courierstatus',
            name='updated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customer',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='courier',
            name='vendor_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courierapp.customer'),
        ),
    ]
